# Generated by Django 4.1.4 on 2023-11-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='username',
        ),
    ]
